# Generated by Django 5.2.7 on 2025-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqhei_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CQHEISurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('surveyor_name', models.CharField(max_length=100)),
                ('survey_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('substrate_size', models.CharField(choices=[('large', 'Mostly Large (Fist Size or Bigger)'), ('medium', 'Mostly Medium (Smaller Than Fist, Bigger Than Fingernail)'), ('small', 'Mostly Small (Smaller Than Fingernail, But Still Coarse)'), ('bedrock', 'Dominated By Bedrock'), ('fine', 'Mostly Very Fine, Not Coarse, Sometimes Greasy or Mucky')], max_length=100)),
                ('substrate_smothering', models.BooleanField(default=False, verbose_name='Are fist size and larger pieces smothered by sands/silts?')),
                ('substrate_silting', models.BooleanField(default=False, verbose_name='Are silts and clays distributed throughout stream?')),
                ('cover_roots', models.BooleanField(default=False, verbose_name='Underwater Tree Roots (Large)')),
                ('cover_boulders', models.BooleanField(default=False, verbose_name='Boulders')),
                ('cover_trees', models.BooleanField(default=False, verbose_name='Downed Trees, Logs, Branches')),
                ('cover_plants', models.BooleanField(default=False, verbose_name='Water Plants')),
                ('cover_deep_areas', models.BooleanField(default=False, verbose_name='Deep Areas (Chest Deep)')),
                ('cover_undercut', models.BooleanField(default=False, verbose_name='Undercut Banks')),
                ('cover_rootlets', models.BooleanField(default=False, verbose_name='Underwater Tree Rootlets (Fine)')),
                ('cover_backwaters', models.BooleanField(default=False, verbose_name='Backwaters, Oxbows or Side Channels')),
                ('cover_shallow_slow', models.BooleanField(default=False, verbose_name='Shallow, Slow Areas for Small Fish')),
                ('cover_shrubs', models.BooleanField(default=False, verbose_name='Shrubs, Small Trees That Hang Close Over the Bank')),
                ('stream_shape', models.CharField(choices=[('straight', 'Very Straight'), ('wiggle', 'Mostly Straight Some "Wiggle"'), ('1-2_bends', '1 or 2 Good Bends'), ('2+_bends', '2 or More Good Bends')], max_length=100)),
                ('human_alterations', models.CharField(choices=[('natural', 'Mostly Natural'), ('minor', 'A Few Minor Man-made Changes'), ('many', 'Many Man-made Changes, but still some natural conditions left'), ('heavy', 'Heavy, Man-made Changes')], max_length=100)),
                ('riparian_width', models.CharField(choices=[('wide', "Wide (Can't Throw A Rock Through It)"), ('narrow', 'Narrow (Can Throw A Rock Through It)'), ('none', 'None')], max_length=100)),
                ('riparian_type', models.CharField(choices=[('forest', 'Forest/Wetland'), ('shrubs', 'Shrubs'), ('fields', 'Overgrown Fields'), ('fenced', 'Fenced Pasture'), ('park', 'Park (Grass)'), ('tillage', 'Conservation Tillage'), ('pasture', 'Open Pasture'), ('suburban', 'Suburban'), ('urban', 'Urban Industrial')], max_length=100)),
                ('bank_erosion', models.CharField(choices=[('collapsing', 'Raw, Collapsing Banks'), ('mixed', 'Combination of Stable and Eroding Banks'), ('stable', 'Stable Hard or Well Vegetated Banks')], max_length=100)),
                ('stream_shade', models.CharField(choices=[('mostly', 'Mostly'), ('partly', 'Partly'), ('none', 'None')], max_length=100)),
                ('pool_depth', models.CharField(choices=[('chest', 'Chest Deep'), ('waist', 'Waist Deep'), ('knee', 'Knee Deep'), ('ankle', 'Ankle Deep')], max_length=100)),
                ('flow_very_fast', models.BooleanField(default=False, verbose_name='Very Fast; Hard to Stand in the Current')),
                ('flow_fast', models.BooleanField(default=False, verbose_name='Fast; Quickly Takes Objects Downstream')),
                ('flow_moderate', models.BooleanField(default=False, verbose_name='Moderate; Slowly Takes Objects Downstream')),
                ('flow_slow', models.BooleanField(default=False, verbose_name='Slow; Flow Nearly Absent')),
                ('flow_none', models.BooleanField(default=False, verbose_name='No Flow')),
                ('riffle_depth', models.CharField(choices=[('knee_fast', 'Knee Deep or Deeper & Fast'), ('ankle_fast', 'Ankle/Calf Deep & Fast'), ('ankle_slow', 'Ankle Deep or Less & Slow'), ('none', 'Do Not Exist')], max_length=100)),
                ('riffle_substrate', models.CharField(choices=[('fist', 'Fist Size or Larger'), ('small', 'Smaller Than Fist Size, but Larger Than Fingernail'), ('fine', 'Smaller Than Your Fingernails')], max_length=100)),
            ],
            options={
                'verbose_name': 'CQHEI Survey',
                'verbose_name_plural': 'CQHEI Surveys',
            },
        ),
        migrations.DeleteModel(
            name='BasicSurvey',
        ),
    ]
