# Generated by Django 5.2.7 on 2025-10-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqhei_app', '0002_cqheisurvey_delete_basicsurvey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='flow_fast',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='flow_moderate',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='flow_none',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='flow_slow',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='flow_very_fast',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='surveyor_name',
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='clarity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Clarity'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cluster_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cluster Number'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='flow_type',
            field=models.CharField(choices=[('very_fast', 'Very Fast; Hard to Stand in the Current - 2 pts'), ('fast', 'Fast; Quickly Takes Objects Downstream - 3 pts'), ('moderate', 'Moderate; Slowly Takes Objects Downstream - 1 pt'), ('slow', 'Slow; Flow Nearly Absent - 1 pt'), ('none', 'No Flow - 0 pts')], default='very_fast', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='forest_ule_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Forest/Ule Number'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='name_group',
            field=models.CharField(default='Default Surveyor', max_length=200, verbose_name='Name/Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='reach_length',
            field=models.CharField(choices=[('50m', '50m'), ('100m', '100m'), ('150m', '150m'), ('200m', '200m'), ('500m', '500m'), ('750m', '750m'), ('other', 'Other (specify below)')], default='200m', max_length=20, verbose_name='Length of Reach Evaluated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='reach_length_custom',
            field=models.CharField(blank=True, max_length=100, verbose_name='If Other, specify exact length'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='river_code',
            field=models.CharField(default='RC001', max_length=50, verbose_name='River Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='river_mile',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='River Mile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='river_site',
            field=models.CharField(default='Default River Site', max_length=200, verbose_name='River Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='survey_title',
            field=models.CharField(default="Citizen's Qualitative Habitat Evaluation Index", max_length=200, verbose_name='Survey Title'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='bank_erosion',
            field=models.CharField(choices=[('stable', 'Stable Hard or Well Vegetated Banks - 10 pts'), ('mixed', 'Combination of Stable and Eroding Banks - 5 pts'), ('collapsing', 'Raw, Collapsing Banks - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='human_alterations',
            field=models.CharField(choices=[('natural', 'Mostly Natural - 14 pts'), ('minor', 'A Few Minor Man-made Changes - 10 pts'), ('many', 'Many Man-made Changes, but still some natural conditions left - 6 pts'), ('heavy', 'Heavy, Man-made Changes - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='pool_depth',
            field=models.CharField(choices=[('chest', 'Chest Deep - 8 pts'), ('waist', 'Waist Deep - 6 pts'), ('knee', 'Knee Deep - 4 pts'), ('ankle', 'Ankle Deep - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='riffle_depth',
            field=models.CharField(choices=[('knee_fast', 'Knee Deep or Deeper & Fast - 8 pts'), ('ankle_fast', 'Ankle/Calf Deep & Fast - 6 pts'), ('ankle_slow', 'Ankle Deep or Less & Slow - 4 pts'), ('none', 'Do Not Exist - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='riffle_substrate',
            field=models.CharField(choices=[('fist', 'Fist Size or Larger - 7 pts'), ('small', 'Smaller Than Fist Size, but Larger Than Fingernail - 4 pts'), ('fine', 'Smaller Than Your Fingernails - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='riparian_type',
            field=models.CharField(choices=[('forest', 'Forest/Wetland - 10 pts'), ('shrubs', 'Shrubs - 8 pts'), ('fields', 'Overgrown Fields - 6 pts'), ('fenced', 'Fenced Pasture - 5 pts'), ('park', 'Park (Grass) - 4 pts'), ('tillage', 'Conservation Tillage - 3 pts'), ('pasture', 'Open Pasture - 2 pts'), ('suburban', 'Suburban - 1 pt'), ('urban', 'Urban Industrial - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='riparian_width',
            field=models.CharField(choices=[('wide', "Wide (Can't Throw A Rock Through It) - 10 pts"), ('narrow', 'Narrow (Can Throw A Rock Through It) - 6 pts'), ('none', 'None - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='stream_shade',
            field=models.CharField(choices=[('mostly', 'Mostly - 3 pts'), ('partly', 'Partly - 2 pts'), ('none', 'None - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='stream_shape',
            field=models.CharField(choices=[('straight', 'Very Straight - 0 pts'), ('wiggle', 'Mostly Straight Some "Wiggle" - 3 pts'), ('1-2_bends', '1 or 2 Good Bends - 7 pts'), ('2+_bends', '2 or More Good Bends - 10 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='substrate_size',
            field=models.CharField(choices=[('large', 'Mostly Large (Fist Size or Bigger) - 14 pts'), ('medium', 'Mostly Medium (Smaller Than Fist, Bigger Than Fingernail) - 10 pts'), ('small', 'Mostly Small (Smaller Than Fingernail, But Still Coarse) - 7 pts'), ('bedrock', 'Dominated By Bedrock - 3 pts'), ('fine', 'Mostly Very Fine, Not Coarse, Sometimes Greasy or Mucky - 0 pts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='survey_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
