# Generated by Django 5.2.7 on 2025-10-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqhei_app', '0003_remove_cqheisurvey_flow_fast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='bank_erosion',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_plants',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_rootlets',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_roots',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_shrubs',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_trees',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_undercut',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='flow_type',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='human_alterations',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='pool_depth',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='riffle_depth',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='riffle_substrate',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='riparian_type',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='riparian_width',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='stream_shade',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='stream_shape',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='substrate_silting',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='substrate_size',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='substrate_smothering',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='survey_title',
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_downed_trees',
            field=models.BooleanField(default=False, verbose_name='Downed trees/logs - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_shrubs_trees',
            field=models.BooleanField(default=False, verbose_name='Shrubs/trees hanging in water - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_tree_rootlets',
            field=models.BooleanField(default=False, verbose_name='Tree rootlets - 3 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_tree_roots_large',
            field=models.BooleanField(default=False, verbose_name='Large tree roots - 9 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_undercut_banks',
            field=models.BooleanField(default=False, verbose_name='Undercut banks - 7 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_water_plants',
            field=models.BooleanField(default=False, verbose_name='Water plants - 1 pt'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='curviness_mostly_straight',
            field=models.BooleanField(default=False, verbose_name='Mostly straight - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='curviness_one_two_bends',
            field=models.BooleanField(default=False, verbose_name='1-2 bends in reach - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='curviness_two_plus_bends',
            field=models.BooleanField(default=False, verbose_name='2+ bends in reach - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='curviness_very_straight',
            field=models.BooleanField(default=False, verbose_name='Very straight - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='depth_ankle',
            field=models.BooleanField(default=False, verbose_name='Ankle deep or less - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='depth_chest',
            field=models.BooleanField(default=False, verbose_name='Chest deep or more - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='depth_knee',
            field=models.BooleanField(default=False, verbose_name='Knee deep - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='depth_waist',
            field=models.BooleanField(default=False, verbose_name='Waist deep - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='erosion_open_pasture',
            field=models.BooleanField(default=False, verbose_name='Open pasture - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='erosion_raw_collapsing',
            field=models.BooleanField(default=False, verbose_name='Raw, collapsing banks - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='erosion_suburban',
            field=models.BooleanField(default=False, verbose_name='Suburban/lawn - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='erosion_urban',
            field=models.BooleanField(default=False, verbose_name='Urban runoff - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='flow_fast',
            field=models.BooleanField(default=False, verbose_name='Fast - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='flow_moderate',
            field=models.BooleanField(default=False, verbose_name='Moderate - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='flow_none',
            field=models.BooleanField(default=False, verbose_name='None (stagnant) - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='flow_slow',
            field=models.BooleanField(default=False, verbose_name='Slow - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='flow_very_fast',
            field=models.BooleanField(default=False, verbose_name='Very fast - 8 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_conservation_tillage',
            field=models.BooleanField(default=False, verbose_name='Conservation tillage - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_fenced_pasture',
            field=models.BooleanField(default=False, verbose_name='Fenced pasture - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_forest',
            field=models.BooleanField(default=False, verbose_name='Forest - 7 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_open_pasture',
            field=models.BooleanField(default=False, verbose_name='Open pasture/cropland - 1 pt'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_overgrown_fields',
            field=models.BooleanField(default=False, verbose_name='Overgrown fields - 3 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_park',
            field=models.BooleanField(default=False, verbose_name='Park/lawn - 5 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_shrubs',
            field=models.BooleanField(default=False, verbose_name='Shrubs - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_urban',
            field=models.BooleanField(default=False, verbose_name='Urban/industrial - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='natural_heavy_changes',
            field=models.BooleanField(default=False, verbose_name='Heavy changes (concrete, etc.) - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='natural_many_changes',
            field=models.BooleanField(default=False, verbose_name='Many changes (rip-rap, etc.) - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='natural_minor_changes',
            field=models.BooleanField(default=False, verbose_name='Minor changes (some rip-rap) - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='natural_mostly_natural',
            field=models.BooleanField(default=False, verbose_name='Mostly natural - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='riffles_ankle_calf_fast',
            field=models.BooleanField(default=False, verbose_name='Ankle to calf, fast - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='riffles_ankle_shallow_slow',
            field=models.BooleanField(default=False, verbose_name='Ankle to calf, shallow, slow - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='riffles_knee_deep_fast',
            field=models.BooleanField(default=False, verbose_name='Knee deep, fast - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='riffles_none',
            field=models.BooleanField(default=False, verbose_name='None - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='shading_mostly',
            field=models.BooleanField(default=False, verbose_name='Mostly (>75%) - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='shading_none',
            field=models.BooleanField(default=False, verbose_name='None (<25%) - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='shading_partly',
            field=models.BooleanField(default=False, verbose_name='Partly (25-75%) - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='silting_no',
            field=models.BooleanField(default=False, verbose_name='No - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='silting_yes',
            field=models.BooleanField(default=False, verbose_name='Yes (silt present) - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='smothering_no',
            field=models.BooleanField(default=False, verbose_name='No - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='smothering_yes',
            field=models.BooleanField(default=False, verbose_name='Yes (algae, etc.) - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_bedrock',
            field=models.BooleanField(default=False, verbose_name='Bedrock (solid rock bottom) - 8 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_fine',
            field=models.BooleanField(default=False, verbose_name='Fine (silt, mud, sand) - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_fist_size',
            field=models.BooleanField(default=False, verbose_name='Fist size or larger - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_large',
            field=models.BooleanField(default=False, verbose_name='Large (boulders, large rubble) - 6 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_medium',
            field=models.BooleanField(default=False, verbose_name='Medium (cobble, rubble) - 4 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_small',
            field=models.BooleanField(default=False, verbose_name='Small (gravel, small stones) - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_smaller_fingernail',
            field=models.BooleanField(default=False, verbose_name='Smaller than fingernail - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_smaller_fist',
            field=models.BooleanField(default=False, verbose_name='Smaller than fist - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='width_narrow',
            field=models.BooleanField(default=False, verbose_name='Narrow (5-15m) - 2 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='width_none',
            field=models.BooleanField(default=False, verbose_name='None (<5m) - 0 pts'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='width_wide',
            field=models.BooleanField(default=False, verbose_name='Wide (>15m) - 4 pts'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_backwaters',
            field=models.BooleanField(default=False, verbose_name='Backwaters - 4 pts'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_boulders',
            field=models.BooleanField(default=False, verbose_name='Boulders - 8 pts'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_deep_areas',
            field=models.BooleanField(default=False, verbose_name='Deep areas (>1m) - 5 pts'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_shallow_slow',
            field=models.BooleanField(default=False, verbose_name='Shallow, slow water - 0 pts'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='reach_length',
            field=models.CharField(choices=[('50m', '50m'), ('100m', '100m'), ('150m', '150m'), ('200m', '200m'), ('500m', '500m'), ('750m', '750m'), ('other', 'Other')], max_length=20, verbose_name='Length of Reach Evaluated'),
        ),
    ]
