# Generated by Django 5.2.7 on 2025-10-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqhei_app', '0004_remove_cqheisurvey_bank_erosion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_deep_areas',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_shallow_slow',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_shrubs_trees',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_tree_rootlets',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_tree_roots_large',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_undercut_banks',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_water_plants',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='curviness_one_two_bends',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='curviness_two_plus_bends',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='depth_ankle',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='depth_chest',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='depth_knee',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='depth_waist',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='erosion_suburban',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='erosion_urban',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='landuse_forest',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='landuse_open_pasture',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='landuse_urban',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='substrate_bedrock',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='substrate_fine',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='substrate_large',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='substrate_medium',
        ),
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='substrate_small',
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_shallow_slow_areas',
            field=models.BooleanField(default=False, verbose_name='Shallow, Slow Areas for Small Fish'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_shrubs_small_trees',
            field=models.BooleanField(default=False, verbose_name='Shrubs, Small Trees That Hang Close Over the Bank'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_underwater_tree_roots',
            field=models.BooleanField(default=False, verbose_name='Underwater Tree Roots (Large) - Deep Areas (Chest Deep)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='curviness_one_two_good_bends',
            field=models.BooleanField(default=False, verbose_name='1 or 2 Good Bends (6 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='curviness_two_plus_good_bends',
            field=models.BooleanField(default=False, verbose_name='2 or More Good Bends (9 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='depth_ankle_deep',
            field=models.BooleanField(default=False, verbose_name='Ankle Deep (0 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='depth_chest_deep',
            field=models.BooleanField(default=False, verbose_name='Chest Deep (8 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='depth_knee_deep',
            field=models.BooleanField(default=False, verbose_name='Knee Deep (4 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='depth_waist_deep',
            field=models.BooleanField(default=False, verbose_name='Waist Deep (6 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='erosion_suburban_rowcrop',
            field=models.BooleanField(default=False, verbose_name='Suburban - Rowcrop (0 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='erosion_urban_industrial',
            field=models.BooleanField(default=False, verbose_name='Urban/Industrial - Stable Hard or Well Vegetated Banks (4 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='landuse_forest_wetland',
            field=models.BooleanField(default=False, verbose_name='Forest/Wetland (5 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_dominated_bedrock',
            field=models.BooleanField(default=False, verbose_name='Dominated By Bedrock (3 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_mostly_large',
            field=models.BooleanField(default=False, verbose_name='Mostly Large Fist Size or Bigger (14 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_mostly_medium',
            field=models.BooleanField(default=False, verbose_name='Mostly Medium Smaller Than Fist But Bigger Than Fingernail (10 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_mostly_small',
            field=models.BooleanField(default=False, verbose_name='Mostly Small Smaller Than Fingernail, But Still Coarse (6 pts)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='substrate_mostly_very_fine',
            field=models.BooleanField(default=False, verbose_name='Mostly Very Fine, Not Coarse, Sometimes Greasy or Mucky (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_backwaters',
            field=models.BooleanField(default=False, verbose_name='Backwaters, Oxbows or Side Channels'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_boulders',
            field=models.BooleanField(default=False, verbose_name='Boulders - Undercut Banks'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_downed_trees',
            field=models.BooleanField(default=False, verbose_name='Downed Trees, Logs, Branches - Water Plants'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='curviness_mostly_straight',
            field=models.BooleanField(default=False, verbose_name="Mostly Straight Some 'Wiggle' (3 pts)"),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='curviness_very_straight',
            field=models.BooleanField(default=False, verbose_name='Very Straight (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='erosion_open_pasture',
            field=models.BooleanField(default=False, verbose_name='Open Pasture - Combination of Stable and Eroding Banks (2 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='erosion_raw_collapsing',
            field=models.BooleanField(default=False, verbose_name='Raw, Collapsing Banks (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='flow_fast',
            field=models.BooleanField(default=False, verbose_name='Fast: Quickly Takes Objects Downstream (3 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='flow_moderate',
            field=models.BooleanField(default=False, verbose_name='Moderate: Slowly Takes Objects Downstream (1 pt)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='flow_none',
            field=models.BooleanField(default=False, verbose_name='No Flow (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='flow_slow',
            field=models.BooleanField(default=False, verbose_name='Slow: Flow Nearly Absent (1 pt)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='flow_very_fast',
            field=models.BooleanField(default=False, verbose_name='Very Fast: Hard to Stand in the Water (2 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='landuse_conservation_tillage',
            field=models.BooleanField(default=False, verbose_name='Conservation Tillage (2 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='landuse_fenced_pasture',
            field=models.BooleanField(default=False, verbose_name='Fenced Pasture (2 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='landuse_overgrown_fields',
            field=models.BooleanField(default=False, verbose_name='Overgrown Fields (3 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='landuse_park',
            field=models.BooleanField(default=False, verbose_name='Park (Grass) (2 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='landuse_shrubs',
            field=models.BooleanField(default=False, verbose_name='Shrubs (4 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='natural_heavy_changes',
            field=models.BooleanField(default=False, verbose_name='Heavy, Man-made Changes (e.g., channelized, leveed.) (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='natural_many_changes',
            field=models.BooleanField(default=False, verbose_name='Many Man-made Changes, but still some natural conditions left (e.g., trees, meanders) (6 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='natural_minor_changes',
            field=models.BooleanField(default=False, verbose_name='A Few Minor Man-made Changes (e.g., bridge, some streambank changes) (9 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='natural_mostly_natural',
            field=models.BooleanField(default=False, verbose_name='Mostly Natural (12 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='riffles_ankle_calf_fast',
            field=models.BooleanField(default=False, verbose_name='Ankle/Calf Deep & Fast (6 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='riffles_ankle_shallow_slow',
            field=models.BooleanField(default=False, verbose_name='Ankle Deep or Less & Slow (4 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='riffles_knee_deep_fast',
            field=models.BooleanField(default=False, verbose_name='Knee Deep or Deeper & Fast (8 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='riffles_none',
            field=models.BooleanField(default=False, verbose_name='Do Not Exist (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='shading_mostly',
            field=models.BooleanField(default=False, verbose_name='Mostly (3 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='shading_none',
            field=models.BooleanField(default=False, verbose_name='None (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='shading_partly',
            field=models.BooleanField(default=False, verbose_name='Partly (2 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='silting_no',
            field=models.BooleanField(default=False, verbose_name='No (10 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='silting_yes',
            field=models.BooleanField(default=False, verbose_name='Yes (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='smothering_no',
            field=models.BooleanField(default=False, verbose_name='No (10 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='smothering_yes',
            field=models.BooleanField(default=False, verbose_name='Yes (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='substrate_fist_size',
            field=models.BooleanField(default=False, verbose_name='Fist Size or Larger (7 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='substrate_smaller_fingernail',
            field=models.BooleanField(default=False, verbose_name='Smaller Than Your Fingernails (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='substrate_smaller_fist',
            field=models.BooleanField(default=False, verbose_name='Smaller Than Fist Size, but Larger Than Fingernail (4 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='width_narrow',
            field=models.BooleanField(default=False, verbose_name='Narrow (Can Throw A Rock Through It) (5 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='width_none',
            field=models.BooleanField(default=False, verbose_name='None (0 pts)'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='width_wide',
            field=models.BooleanField(default=False, verbose_name="Wide (Can't Throw A Rock Through It) (9 pts)"),
        ),
    ]
