# Generated by Django 5.2.7 on 2025-10-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqhei_app', '0005_remove_cqheisurvey_cover_deep_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cqheisurvey',
            name='cover_underwater_tree_roots',
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_deep_areas',
            field=models.BooleanField(default=False, verbose_name='Deep Areas (Chest Deep)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_undercut_banks',
            field=models.BooleanField(default=False, verbose_name='Undercut Banks'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_underwater_tree_rootlets',
            field=models.BooleanField(default=False, verbose_name='Underwater Tree Rootlets (Fine)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_underwater_tree_roots_large',
            field=models.BooleanField(default=False, verbose_name='Underwater Tree Roots (Large)'),
        ),
        migrations.AddField(
            model_name='cqheisurvey',
            name='cover_water_plants',
            field=models.BooleanField(default=False, verbose_name='Water Plants'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_boulders',
            field=models.BooleanField(default=False, verbose_name='Boulders'),
        ),
        migrations.AlterField(
            model_name='cqheisurvey',
            name='cover_downed_trees',
            field=models.BooleanField(default=False, verbose_name='Downed Trees, Logs, Branches'),
        ),
    ]
